spring.application.name=product-service

### Production ###

spring.datasource.url=postgresql://product_db_6466_user:zFeG6MnQTHkLQwqeyi9S6c3oQYXBzoVH@dpg-d1b6iube5dus73e9htd0-a/product_db_6466
spring.datasource.username=product_db_6466_user
spring.datasource.password=zFeG6MnQTHkLQwqeyi9S6c3oQYXBzoVH
spring.datasource.driver-class-name=org.postgresql.Driver

##########################

# ddl-update
spring.jpa.hibernate.ddl-auto=update

# Allow Overriding Beans
spring.main.allow-bean-definition-overriding=true