spring.application.name=product-service

### AWS ###
spring.datasource.url=jdbc:postgresql://production.cw94o2cospwg.us-east-1.rds.amazonaws.com:5432/production
spring.datasource.username=master
spring.datasource.password=Lakshay02
spring.datasource.driver-class-name=org.postgresql.Driver


### JPA ###
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=3000