spring.application.name=product-service

### ? Production ###
spring.datasource.url=jdbc:postgresql://dpg-d1b6iube5dus73e9htd0-a/product_db_6466
spring.datasource.username=product_db_6466_user
spring.datasource.password=zFeG6MnQTHkLQwqeyi9S6c3oQYXBzoVH
spring.datasource.driver-class-name=org.postgresql.Driver

### JPA ###
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
